name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t chat-server .
          docker tag chat-server <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/chat-server

      - name: Login to AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region <REGION> | docker login --username AWS --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com

      - name: Push Image to ECR
        run: |
          docker push <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/chat-server

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster chat-cluster --service chat-service --force-new-deployment
